[Animation]
; Keep the explosion frozen on the last frame instead of disappearing. Create a death scene.
EntityExplosionFreeze = true

; Play explosion (bottom) animation at half speed (slower)
EntityExplosionSpeed = 2

; Prevent monsters from exploding when colliding with Chip
MonsterExplodeOnCollision = false

; Play ICChip (collectible chips) animations at half speed (slower). You'll be able to animate Chips
ChipAnimationSpeed = 4
